### ISSUE TITLE
고석영_문제

### ISSUE THREAD

**Issue by 90seok0** [daily-coding-ps/ps#109]
1063 킹
https://www.acmicpc.net/problem/1063

2947 나무조각
https://www.acmicpc.net/problem/2947

8979 올림픽
https://www.acmicpc.net/problem/8979

**Comment by dding94** [comment]
https://www.acmicpc.net/problem/10828

**Comment by sebin1213** [comment]
https://www.acmicpc.net/problem/1966
해당 문제는 큐 관련 문제입니다 명구님이 말씀해 주신것처럼 자료구조 먼저 보시고 스택과 큐의 차이점을 생각하시면서 푸시면 나중에 더욱 도움되실 것 같습니다!
