### ISSUE TITLE
프렌즈4블록

### ISSUE THREAD

**Issue by dding94** [daily-coding-ps/ps#80]
https://programmers.co.kr/learn/courses/30/lessons/17679?language=java

**Comment by sinkyoungdeok** [comment]
@dding94 님 문제가 재밌긴한데 이분탐색문제가 맞을까요 ?
아닌거면 이분탐색문제로 변경가능할까요?

**Comment by dding94** [comment]
@sinkyoungdeok 저번에 회의때 얘기할때 제가 유형 상관없이 가져온다고 말씀드리긴 했는데 바꿀까요??

**Comment by sinkyoungdeok** [comment]
@dding94 아 그랬었나여? 
훔.. 저희가 지금 2회독이긴한데, 2회독 까지는 분류대로 가져오는걸로 정하는건 어떨까요? 아직 분류별로 푸는것도 힘드신분들이 꽤 계신것같아서요 ㅎㅎ
