### ISSUE TITLE
[이분 탐색] 흩날리는 시험지 속에서 내 평점이 느껴진거야

### ISSUE THREAD

**Issue by sebin1213** [daily-coding-ps/ps#82]
문제변경합니다
https://www.acmicpc.net/problem/17951

**Comment by sinkyoungdeok** [comment]
@sebin1213 님 이거 이분탐색 문제가 맞을까요?
아닌지 한번 확인해주시고, 아니라면 다른 이분탐색 문제로 변경이 가능할까요?

**Comment by sebin1213** [comment]
이분탐색으로 풀수있지만 포인터로 더 쉽게 풀수있는 문제네요...! 
문제 변경하겠습니다!
